self:
{
  config,
  lib,
  pkgs,
  ...
}:

let
  cfg = config.programs.lookapp;

  defaultPackage =
    self.packages.${pkgs.stdenv.hostPlatform.system}.default
      or (pkgs.callPackage ./package.nix { });

  themeSettings =
    if cfg.theme == null then
      { }
    else
      {
        ui_theme = cfg.theme;
      }
      // lib.optionalAttrs (cfg.theme == "kindle") {
        ui_tint_opacity = 0.93;
        ui_font_opacity = 1.0;
        ui_border_opacity = 0.26;
      };

  finalSettings = themeSettings // cfg.settings;

  # core splits `ignored_patterns_*` and `alias_*` on `|` (parse_pattern_values)
  # and every other list key on `,` (parse_csv), which also unescapes `\,`/`\\`.
  isPipeSeparated =
    name: lib.hasPrefix "ignored_patterns_" name || lib.hasPrefix "alias_" name;

  escapeCsvEntry = entry: lib.replaceStrings [ "\\" "," ] [ "\\\\" "\\," ] (toString entry);

  formatValue =
    name: value:
    if lib.isBool value then
      lib.boolToString value
    else if !lib.isList value then
      toString value
    else if isPipeSeparated name then
      lib.concatStringsSep "|" (map toString value)
    else
      lib.concatStringsSep "," (map escapeCsvEntry value);

  renderedSettings =
    lib.mapAttrsToList (name: value: "${name}=${formatValue name value}") finalSettings;
    else if lib.isList value then
      lib.concatStringsSep "," (map toString value)
    else
      toString value;

  renderedSettings =
    lib.mapAttrsToList (name: value: "${name}=${formatValue value}") finalSettings;

  renderedAliases =
    lib.mapAttrsToList (
      name: values: "alias_${name}=${lib.concatStringsSep "|" (map toString values)}"
    ) cfg.aliases;

  configText = ''
    # look configuration
    # Generated by Home Manager. Edit your Nix config, not this file.

    ${lib.concatStringsSep "\n" (renderedSettings ++ renderedAliases)}
  '';

  configFile = pkgs.writeText "look.config" configText;

  manageConfig = finalSettings != { } || cfg.aliases != { };
in
{
  options.programs.lookapp = {
    enable = lib.mkEnableOption "Look - keyboard-first desktop launcher";

    package = lib.mkOption {
      type = lib.types.package;
      default = defaultPackage;
      defaultText = lib.literalExpression "inputs.look.packages.\${pkgs.stdenv.hostPlatform.system}.default";
      description = "The Look package to install.";
    };

    theme = lib.mkOption {
      type = lib.types.nullOr (
        lib.types.enum [
          ""
          "tokyo-night"
          "rose-pine"
          "gruvbox"
          "dracula"
          "kanagawa"
          "kindle"
          "custom"
        ]
      );
      default = null;
      example = "kindle";
      description = ''
        Built-in Look theme preset to write as `ui_theme`. `null` leaves the
        theme unmanaged. The empty string selects the default Catppuccin theme.
      '';
    };

    settings = lib.mkOption {
      type = lib.types.attrsOf (
        lib.types.oneOf [
          lib.types.bool
          lib.types.int
          lib.types.float
          lib.types.str
          (lib.types.listOf lib.types.str)
        ]
      );
      default = { };
      example = lib.literalExpression ''
        {
          ui_tint_opacity = 0.93;
          running_apps_placement = "right";
          file_scan_extra_roots = [ "~/Projects" "/mnt/data" ];
          ai_enabled = false;
        }
      '';
      description = ''
        Settings written to ~/.look.config. Attribute names map directly to
        Look config keys, for example `ui_theme` becomes `ui_theme=...`.
        Lists are serialized as comma-separated values, except for
        `ignored_patterns_*` and `alias_*` keys, which Look parses as
        pipe-separated.
      '';
    };

    aliases = lib.mkOption {
      type = lib.types.attrsOf (lib.types.listOf lib.types.str);
      default = { };
      example = lib.literalExpression ''
        {
          note = [ "Obsidian" "Logseq" ];
          term = [ "Alacritty" "Kitty" ];
        }
      '';
      description = ''
        Search aliases written as `alias_<name>=Term1|Term2`.
      '';
    };
  };

  config = lib.mkIf cfg.enable {
    home.packages = [ cfg.package ];

    # Look rewrites ~/.look.config itself on every settings change, so a
    # home.file symlink into the read-only store makes those writes fail - and
    # the frontend only logs the error. Install a mutable copy instead: Nix
    # still wins on each activation, but the app can write between them.
    home.activation.lookappConfig = lib.mkIf manageConfig (
      lib.hm.dag.entryAfter [ "writeBoundary" ] ''
        lookappConfig="$HOME/.look.config"
        if [ -e "$lookappConfig" ] && [ ! -e "$lookappConfig.hm-backup" ]; then
          run cp --no-preserve=mode "$lookappConfig" "$lookappConfig.hm-backup"
        fi
        run install -m 0644 ${configFile} "$lookappConfig"
      ''
    );
  };
  };
}
