use crate::platform::SettingsCatalogEntry;

/// Suffixes match the GNOME catalog where the pane is the same (keeps the Bluetooth quick action).
pub(crate) static KDE_SETTINGS_CATALOG: &[SettingsCatalogEntry] = &[
    // Connectivity
    SettingsCatalogEntry {
        title: "Wi-Fi & Networking",
        target: "kcm_networkmanagement",
        candidate_id_suffix: "network",
        aliases: "wifi wi-fi wireless network ethernet vpn wired connection internet settings",
    },
    SettingsCatalogEntry {
        title: "Bluetooth",
        target: "kcm_bluetooth",
        candidate_id_suffix: "bluetooth",
        aliases: "bluetooth devices pair settings",
    },
    SettingsCatalogEntry {
        title: "Proxy",
        target: "kcm_proxy",
        candidate_id_suffix: "proxy",
        aliases: "proxy network http socks server settings",
    },
    SettingsCatalogEntry {
        title: "Firewall",
        target: "kcm_firewall",
        candidate_id_suffix: "firewall",
        aliases: "firewall network rules ports ufw firewalld security settings",
    },
    SettingsCatalogEntry {
        title: "Mobile Broadband",
        target: "kcm_cellular_network",
        candidate_id_suffix: "wwan",
        aliases: "mobile broadband cellular data sim card wwan settings",
    },
    // Devices
    SettingsCatalogEntry {
        title: "Display & Monitor",
        target: "kcm_kscreen",
        candidate_id_suffix: "display",
        aliases: "monitor screen display resolution refresh rate scale orientation settings",
    },
    SettingsCatalogEntry {
        title: "Night Light",
        target: "kcm_nightlight",
        candidate_id_suffix: "night-light",
        aliases: "night light color temperature blue light display settings",
    },
    SettingsCatalogEntry {
        title: "Sound",
        target: "kcm_pulseaudio",
        candidate_id_suffix: "sound",
        aliases: "audio volume speaker microphone output input device settings",
    },
    SettingsCatalogEntry {
        title: "Power Management",
        target: "kcm_powerdevilprofilesconfig",
        candidate_id_suffix: "power",
        aliases: "power battery energy suspend sleep hibernate screen dim lid settings",
    },
    SettingsCatalogEntry {
        title: "Keyboard",
        target: "kcm_keyboard",
        candidate_id_suffix: "keyboard",
        aliases: "keyboard input layout language repeat numlock settings",
    },
    SettingsCatalogEntry {
        title: "Shortcuts",
        target: "kcm_keys",
        candidate_id_suffix: "shortcuts",
        aliases: "keyboard shortcuts hotkeys keybinding global settings",
    },
    SettingsCatalogEntry {
        title: "Mouse",
        target: "kcm_mouse",
        candidate_id_suffix: "mouse",
        aliases: "mouse pointer speed acceleration buttons scroll settings",
    },
    SettingsCatalogEntry {
        title: "Touchpad",
        target: "kcm_touchpad",
        candidate_id_suffix: "touchpad",
        aliases: "touchpad trackpad tap scroll gestures pointer speed settings",
    },
    SettingsCatalogEntry {
        title: "Drawing Tablet",
        target: "kcm_tablet",
        candidate_id_suffix: "wacom",
        aliases: "wacom drawing tablet pen stylus pressure settings",
    },
    SettingsCatalogEntry {
        title: "Game Controller",
        target: "kcm_gamecontroller",
        candidate_id_suffix: "game-controller",
        aliases: "game controller gamepad joystick test settings",
    },
    SettingsCatalogEntry {
        title: "Printers",
        target: "kcm_printer_manager",
        candidate_id_suffix: "printers",
        aliases: "printer print queue cups devices settings",
    },
    SettingsCatalogEntry {
        title: "Removable Storage",
        target: "kcm_device_automounter",
        candidate_id_suffix: "automount",
        aliases: "removable storage usb disk automount mount devices settings",
    },
    SettingsCatalogEntry {
        title: "Thunderbolt",
        target: "kcm_bolt",
        candidate_id_suffix: "thunderbolt",
        aliases: "thunderbolt devices dock authorize settings",
    },
    // Appearance
    SettingsCatalogEntry {
        title: "Global Theme",
        target: "kcm_lookandfeel",
        candidate_id_suffix: "appearance",
        aliases: "appearance global theme look and feel dark light style settings",
    },
    SettingsCatalogEntry {
        title: "Colors",
        target: "kcm_colors",
        candidate_id_suffix: "colors",
        aliases: "colors color scheme accent dark light appearance settings",
    },
    SettingsCatalogEntry {
        title: "Wallpaper",
        target: "kcm_wallpaper",
        candidate_id_suffix: "wallpaper",
        aliases: "wallpaper background desktop picture appearance settings",
    },
    SettingsCatalogEntry {
        title: "Plasma Style",
        target: "kcm_desktoptheme",
        candidate_id_suffix: "plasma-style",
        aliases: "plasma style desktop theme panel appearance settings",
    },
    SettingsCatalogEntry {
        title: "Application Style",
        target: "kcm_style",
        candidate_id_suffix: "app-style",
        aliases: "application style widget theme gtk qt appearance settings",
    },
    SettingsCatalogEntry {
        title: "Window Decorations",
        target: "kcm_kwindecoration",
        candidate_id_suffix: "window-decorations",
        aliases: "window decorations titlebar borders buttons appearance settings",
    },
    SettingsCatalogEntry {
        title: "Fonts",
        target: "kcm_fonts",
        candidate_id_suffix: "fonts",
        aliases: "fonts font size antialiasing hinting dpi appearance settings",
    },
    SettingsCatalogEntry {
        title: "Font Management",
        target: "kcm_fontinst",
        candidate_id_suffix: "font-management",
        aliases: "font install manage preview fonts settings",
    },
    SettingsCatalogEntry {
        title: "Icons",
        target: "kcm_icons",
        candidate_id_suffix: "icons",
        aliases: "icons icon theme appearance settings",
    },
    SettingsCatalogEntry {
        title: "Cursors",
        target: "kcm_cursortheme",
        candidate_id_suffix: "cursors",
        aliases: "cursor mouse pointer theme size appearance settings",
    },
    SettingsCatalogEntry {
        title: "Splash Screen",
        target: "kcm_splashscreen",
        candidate_id_suffix: "splash-screen",
        aliases: "splash screen startup login appearance settings",
    },
    SettingsCatalogEntry {
        title: "Animations",
        target: "kcm_animations",
        candidate_id_suffix: "animations",
        aliases: "animation speed reduce motion appearance settings",
    },
    // Workspace
    SettingsCatalogEntry {
        title: "General Behavior",
        target: "kcm_workspace",
        candidate_id_suffix: "workspace",
        aliases: "workspace general behavior click files folders single double settings",
    },
    SettingsCatalogEntry {
        title: "Desktop Effects",
        target: "kcm_kwin_effects",
        candidate_id_suffix: "desktop-effects",
        aliases: "desktop effects kwin compositor blur wobbly settings",
    },
    SettingsCatalogEntry {
        title: "Screen Edges",
        target: "kcm_kwinscreenedges",
        candidate_id_suffix: "screen-edges",
        aliases: "screen edges hot corners active corner settings",
    },
    SettingsCatalogEntry {
        title: "Virtual Desktops",
        target: "kcm_kwin_virtualdesktops",
        candidate_id_suffix: "multitasking",
        aliases: "virtual desktops workspaces multitasking settings",
    },
    SettingsCatalogEntry {
        title: "Task Switcher",
        target: "kcm_kwintabbox",
        candidate_id_suffix: "task-switcher",
        aliases: "task switcher alt tab window switching settings",
    },
    SettingsCatalogEntry {
        title: "Window Behavior",
        target: "kcm_kwinoptions",
        candidate_id_suffix: "window-behavior",
        aliases: "window behavior focus actions moving placement settings",
    },
    SettingsCatalogEntry {
        title: "Window Rules",
        target: "kcm_kwinrules",
        candidate_id_suffix: "window-rules",
        aliases: "window rules specific application settings",
    },
    SettingsCatalogEntry {
        title: "Activities",
        target: "kcm_activities",
        candidate_id_suffix: "activities",
        aliases: "activities workspace focus settings",
    },
    SettingsCatalogEntry {
        title: "Notifications",
        target: "kcm_notifications",
        candidate_id_suffix: "notifications",
        aliases: "notifications alerts do not disturb popups settings",
    },
    SettingsCatalogEntry {
        title: "Plasma Search",
        target: "kcm_plasmasearch",
        candidate_id_suffix: "search",
        aliases: "search krunner plugins results settings",
    },
    SettingsCatalogEntry {
        title: "File Search",
        target: "kcm_baloofile",
        candidate_id_suffix: "file-search",
        aliases: "file search baloo index indexing settings",
    },
    SettingsCatalogEntry {
        title: "Session",
        target: "kcm_smserver",
        candidate_id_suffix: "session",
        aliases: "session login logout restore shutdown startup settings",
    },
    // Apps
    SettingsCatalogEntry {
        title: "Default Applications",
        target: "kcm_componentchooser",
        candidate_id_suffix: "applications",
        aliases: "default applications apps browser email file manager terminal settings",
    },
    SettingsCatalogEntry {
        title: "File Associations",
        target: "kcm_filetypes",
        candidate_id_suffix: "file-associations",
        aliases: "file associations file types mime open with settings",
    },
    SettingsCatalogEntry {
        title: "Autostart",
        target: "kcm_autostart",
        candidate_id_suffix: "autostart",
        aliases: "autostart startup login applications scripts settings",
    },
    SettingsCatalogEntry {
        title: "Application Permissions",
        target: "kcm_app-permissions",
        candidate_id_suffix: "app-permissions",
        aliases: "application permissions flatpak sandbox access settings",
    },
    SettingsCatalogEntry {
        title: "Online Accounts",
        target: "kcm_kaccounts",
        candidate_id_suffix: "online-accounts",
        aliases: "online accounts google nextcloud owncloud email cloud settings",
    },
    SettingsCatalogEntry {
        title: "Web Search Keywords",
        target: "kcm_webshortcuts",
        candidate_id_suffix: "web-search-keywords",
        aliases: "web search keywords shortcuts browser settings",
    },
    SettingsCatalogEntry {
        title: "Spell Check",
        target: "kcmspellchecking",
        candidate_id_suffix: "spell-check",
        aliases: "spell check spelling dictionary language settings",
    },
    // Privacy & Security
    SettingsCatalogEntry {
        title: "Screen Locking",
        target: "kcm_screenlocker",
        candidate_id_suffix: "screen-lock",
        aliases: "screen lock locking password timeout privacy security settings",
    },
    SettingsCatalogEntry {
        title: "Recent Files",
        target: "kcm_recentFiles",
        candidate_id_suffix: "privacy",
        aliases: "recent files history activity privacy settings",
    },
    SettingsCatalogEntry {
        title: "Remote Desktop",
        target: "kcm_krdpserver",
        candidate_id_suffix: "sharing",
        aliases: "remote desktop rdp sharing screen settings",
    },
    SettingsCatalogEntry {
        title: "User Feedback",
        target: "kcm_feedback",
        candidate_id_suffix: "feedback",
        aliases: "user feedback telemetry privacy statistics settings",
    },
    // Accessibility
    SettingsCatalogEntry {
        title: "Accessibility",
        target: "kcm_access",
        candidate_id_suffix: "universal-access",
        aliases: "accessibility bell modifier keys sticky slow keys zoom screen reader settings",
    },
    SettingsCatalogEntry {
        title: "Virtual Keyboard",
        target: "kcm_virtualkeyboard",
        candidate_id_suffix: "virtual-keyboard",
        aliases: "virtual keyboard on-screen osk touch input settings",
    },
    // System
    SettingsCatalogEntry {
        title: "Users",
        target: "kcm_users",
        candidate_id_suffix: "users",
        aliases: "user accounts login password avatar fingerprint settings",
    },
    SettingsCatalogEntry {
        title: "Date & Time",
        target: "kcm_clock",
        candidate_id_suffix: "datetime",
        aliases: "date time timezone clock ntp automatic settings",
    },
    SettingsCatalogEntry {
        title: "Region & Language",
        target: "kcm_regionandlang",
        candidate_id_suffix: "region",
        aliases: "region language locale format numbers currency settings",
    },
    SettingsCatalogEntry {
        title: "Input Method",
        target: "kcm_fcitx5",
        candidate_id_suffix: "input-method",
        aliases: "input method fcitx ime chinese japanese korean typing settings",
    },
    SettingsCatalogEntry {
        title: "Login Screen",
        target: "kcm_sddm",
        candidate_id_suffix: "login-screen",
        aliases: "login screen sddm display manager greeter settings",
    },
    SettingsCatalogEntry {
        title: "Login Manager",
        target: "kcm_plasmalogin",
        candidate_id_suffix: "login-manager",
        aliases: "login manager plasma login greeter display manager settings",
    },
    SettingsCatalogEntry {
        title: "Software Update",
        target: "kcm_updates",
        candidate_id_suffix: "updates",
        aliases: "software update updates upgrade discover packages settings",
    },
    SettingsCatalogEntry {
        title: "Background Services",
        target: "kcm_kded",
        candidate_id_suffix: "background-services",
        aliases: "background services kded daemon startup settings",
    },
    SettingsCatalogEntry {
        title: "Personal Folders",
        target: "kcm_desktoppaths",
        candidate_id_suffix: "personal-folders",
        aliases: "personal folders paths desktop documents downloads xdg settings",
    },
    SettingsCatalogEntry {
        title: "About This System",
        target: "kcm_about-distro",
        candidate_id_suffix: "system",
        aliases: "about system information hardware os version distro kernel settings",
    },
];
