# Static-link the MSVC C runtime into Windows binaries so they don't import
# VCRUNTIME140.dll / MSVCP140.dll at load time. Rust defaults crt-static off for
# MSVC, so without this a machine lacking the Microsoft Visual C++
# Redistributable can't start the app, and the NSIS installer doesn't ship it.
# Target-scoped so macOS/Linux builds are unaffected.
[target.x86_64-pc-windows-msvc]
rustflags = ["-C", "target-feature=+crt-static"]

[target.aarch64-pc-windows-msvc]
rustflags = ["-C", "target-feature=+crt-static"]
